// lr_wdo_InstructionSets.h -- String constant definitions for all instructions of lrWindowDo()
// 
//      Copyright (c) 2022-2023 LoveRain Yanghuanhuan 3347484963@qq.com.  All rights reserved.
// 
#pragma once

#ifndef WDO_INSTRUCTION_H
#define WDO_INSTRUCTION_H

#define WDOINS_ECHO				"ECHO"
#define WDOINS_CD				"CD"
#define WDOINS_CLIP				"CLIP"
#define WDOINS_STARTUP			"STARTUP"
#define WDOINS_PAUSE			"PAUSE"
#define WDOINS_DELAY			"DELAY"
#define WDOINS_MUSIC			"MUSIC"
#define WDOINS_BEEP				"BEEP"
#define WDOINS_CALL				"CALL"
#define WDOINS_CMD				"CMD"
#define WDOINS_MCI				"MCI"
#define WDOINS_HELP				"HELP"
#define WDOINS_EXIT				"EXIT"
#define WDOINS_EXITASK			"EXITASK"
#define WDOINS_ABOUT			"ABOUT"
#define WDOINS_ALIAS_APPLY		""		"ALIAS"
#define WDOINS_ALIAS_GET		"GET"	"ALIAS"
#define WDOINS_ALIAS_SET		"SET"	"ALIAS"
#define WDOINS_ALIAS_SETUP		"SETUP"	"ALIAS"
#define	WDOINS_ALIAS_SEE		"SEE"	"ALIAS"
#define	WDOINS_ALIAS_SAVE		"SAVE"	"ALIAS"
#define	WDOINS_ALIAS_LOAD		"LOAD"	"ALIAS"
#define	WDOINS_PTR				"PTR"
#define	WDOINS_UPDATEPTR		"UPDATEPTR"
#define	WDOINS_OPEN				"OPEN"
#define	WDOINS_LIST				"LIST"
#define	WDOINS_INFO				"INFO"
#define	WDOINS_TITLE			"TITLE"
#define WDOINS_TOP				"TOP"
#define WDOINS_TOPMOST			"TOPMOST"
#define WDOINS_BOTTOM			"BOTTOM"
#define WDOINS_ACTIVE			"ACTIVE"
#define WDOINS_FOCUS			"FOCUS"
#define WDOINS_CAPTURE			"CAPTURE"
#define	WDOINS_TRANSP			"TRANSP"
#define	WDOINS_ERASE			"ERASE"
#define WDOINS_TRANSPERASE		"TRANSP_ERASE"
#define	WDOINS_SEND				"SEND"
#define WDOINS_TOPSEND			"TOP_SEND"
#define	WDOINS_OUT				"OUT"
#define	WDOINS_DRAW				"DRAW"
#define WDOINS_IMAGE			"IMAGE"
#define WDOINS_IMAGES			"IMAGES"
#define	WDOINS_PROJECT			"PROJECT"
#define	WDOINS_PARENT			"PARENT"
#define WDOINS_CHILD			"CHILD"
#define	WDOINS_COPY				"COPY"
#define	WDOINS_MOVE				"MOVE"
#define	WDOINS_MOVEX			"MOVEX"
#define	WDOINS_MOVEY			"MOVEY"
#define	WDOINS_POS				"POS"
#define	WDOINS_POSX				"POSX"
#define	WDOINS_POSY				"POSY"
#define	WDOINS_RPOS				"RPOS"
#define	WDOINS_ZOOM				"ZOOM"
#define	WDOINS_ZOOMX			"ZOOMX"
#define	WDOINS_ZOOMY			"ZOOMY"
#define WDOINS_SIZE				"SIZE"
#define	WDOINS_SIZEX			"SIZEX"
#define	WDOINS_SIZEY			"SIZEY"
#define	WDOINS_SHOW				"SHOW"
#define	WDOINS_STYLE			"STYLE"
#define	WDOINS_MAX				"MAX"
#define	WDOINS_MIN				"MIN"
#define WDOINS_FLASH			"FLASH"
#define WDOINS_STROKE			"STROKE"
#define WDOINS_FILL				"FILL"
#define	WDOINS_RESTORE			"RESTORE"
#define	WDOINS_REPAINT			"REPAINT"
#define	WDOINS_DRIFT			"DRIFT"
#define	WDOINS_FOLLOW			"FOLLOW"
#define	WDOINS_WIGGLE			"WIGGLE"
#define	WDOINS_ASIDE			"ASIDE"
#define WDOINS_PUSH				"PUSH"
#define WDOINS_COLLIDE			"COLLIDE"
#define	WDOINS_LOCKPAINT		"LOCKPAINT"
#define	WDOINS_CLOSE			"CLOSE"
#define	WDOINS_CUR_MOVE			"CUR"	"MOVE"
#define	WDOINS_CUR_MOVEX		"CUR"	"MOVEX"
#define	WDOINS_CUR_MOVEY		"CUR"	"MOVEY"
#define	WDOINS_CUR_POS			"CUR"	"POS"
#define	WDOINS_CUR_POSX			"CUR"	"POSX"
#define	WDOINS_CUR_POSY			"CUR"	"POSY"
#define	WDOINS_CUR_RPOS			"CUR"	"RPOS"
#define	WDOINS_CUR_CPOS			"CUR"	"CPOS"
#define	WDOINS_CUR_CRPOS		"CUR"	"CRPOS"
#define	WDOINS_CUR_KEY			"CUR"	"KEY"
#define	WDOINS_CUR_DRIFT		"CUR"	"DRIFT"
#define	WDOINS_CUR_WIGGLE		"CUR"	"WIGGLE"
#define	WDOINS_CUR_RECT			"CUR"	"RECT"
#define WDOINS_BOX_BLANK		"BLANK"	"BOX"
#define	WDOINS_BOX_TEXT			"TEXT"	"BOX"
#define	WDOINS_BOX_INFO			"INFO"	"BOX"
#define WDOINS_BOX_LOG			"LOG"	"BOX"
#define	WDOINS_BOX_IMAGE		"IMAGE"	"BOX"
#define	WDOINS_BOX_BLUE			"BLUE"	"BOX"
#define WDOINS_BOX_SET_TEXT		"SET"	"BOX"	"TEXT"
#define	WDOINS_LOOP				"LOOP"
#define WDOINS_RANDOMRUN		"RANDOMRUN"
#define	WDOINS_QUEUE			"QUEUE"
#define	WDOINS_AT				"AT"
#define WDOINS_HOTKEY			"HOTKEY"
#define	WDOINS_THREAD			"THREAD"


#endif